package com.careerpilot.modules.jobmatch.scoring;
import com.careerpilot.config.JobMatchProperties;import com.careerpilot.modules.jobmatch.embedding.EmbeddingService;import com.careerpilot.modules.jobmatch.entity.*;import com.careerpilot.modules.profile.entity.*;import com.careerpilot.modules.resume.entity.*;import org.springframework.stereotype.Service;import java.util.*;
@Service public class JobMatchScoringService{
 private final SkillNormalizer normalizer;private final JobSkillExtractor extractor;private final TextSimilarityService similarity;private final AlignmentService alignment;private final EmbeddingService embeddings;private final JobMatchProperties properties;
 public JobMatchScoringService(SkillNormalizer normalizer,JobSkillExtractor extractor,TextSimilarityService similarity,AlignmentService alignment,EmbeddingService embeddings,JobMatchProperties properties){this.normalizer=normalizer;this.extractor=extractor;this.similarity=similarity;this.alignment=alignment;this.embeddings=embeddings;this.properties=properties;}
 public MatchScore score(String jd,Resume resume,Profile profile,List<UserSkill>profileSkills){String resumeText=resume.getSections().stream().map(ResumeSection::getRawText).filter(Objects::nonNull).reduce("",(a,b)->a+"\n"+b);Set<String>resumeSkills=new LinkedHashSet<>(normalizer.extract(resumeText));profileSkills.forEach(v->resumeSkills.add(normalizer.normalize(v.getSkill().getDisplayName())));List<ExtractedSkill>jobSkills=extractor.extract(jd);List<SkillDecision>decisions=new ArrayList<>();double earned=0,total=0;Set<String>jobNames=new HashSet<>();for(ExtractedSkill skill:jobSkills){jobNames.add(skill.normalized());double weight=importanceWeight(skill.importance());total+=weight;MatchStatus status;if(resumeSkills.contains(skill.normalized())){status=MatchStatus.MATCHED;earned+=weight;}else if(normalizer.related(skill.normalized()).stream().anyMatch(resumeSkills::contains)){status=MatchStatus.PARTIAL;earned+=weight*.5;}else status=MatchStatus.MISSING;SkillPriority priority=priority(skill,status);String evidence="Mentioned "+skill.frequency()+" time"+(skill.frequency()==1?"":"s")+" in the job description; classified as "+skill.importance().name().toLowerCase(Locale.ROOT)+".";String recommendation=status==MatchStatus.MISSING?"Build and document hands-on "+skill.display()+" experience before adding it to your resume.":status==MatchStatus.PARTIAL?"Show direct "+skill.display()+" evidence if you genuinely have that experience.":"Keep a specific, truthful example that demonstrates "+skill.display()+".";decisions.add(new SkillDecision(skill.display(),skill.normalized(),status,skill.importance(),priority,skill.source(),evidence,recommendation));}
  for(String extra:resumeSkills)if(!jobNames.contains(extra))decisions.add(new SkillDecision(normalizer.display(extra),extra,MatchStatus.MATCHED,SkillImportance.OPTIONAL,SkillPriority.LOW,"RESUME_EXTRA","Present in the profile or parsed resume, but not detected in this job description.","Keep it when relevant; prioritize job-specific evidence first."));
  int skillScore=total==0?0:(int)Math.round(earned/total*100),keyword=similarity.tfIdfScore(resumeText,jd);Integer semantic=null;SemanticStatus semanticStatus=SemanticStatus.UNAVAILABLE;var resumeVector=embeddings.embed(limit(resumeText));var jdVector=embeddings.embed(limit(jd));if(resumeVector.isPresent()&&jdVector.isPresent()){semantic=similarity.normalizedCosine(resumeVector.get(),jdVector.get());semanticStatus=SemanticStatus.AVAILABLE;}
  var experience=alignment.experience(jd,profile,resumeText);var education=alignment.education(jd,profile,resumeText);int overall=weighted(skillScore,keyword,semantic,experience.score(),education.score());return new MatchScore(overall,keyword,skillScore,semantic,semanticStatus,experience,education,List.copyOf(decisions),resumeText);}
 private int weighted(int skill,int keyword,Integer semantic,Integer experience,Integer education){var w=properties.weights();double sum=w.skill()+w.keyword(),score=skill*w.skill()+keyword*w.keyword();if(semantic!=null){sum+=w.semantic();score+=semantic*w.semantic();}if(experience!=null){sum+=w.experience();score+=experience*w.experience();}if(education!=null){sum+=w.education();score+=education*w.education();}return sum==0?0:(int)Math.round(score/sum);}
 private SkillPriority priority(ExtractedSkill skill,MatchStatus status){if(status==MatchStatus.MATCHED)return SkillPriority.LOW;if(skill.importance()==SkillImportance.REQUIRED&&(skill.frequency()>1||"QUALIFICATION".equals(skill.source())))return SkillPriority.HIGH;if(skill.importance()==SkillImportance.REQUIRED||skill.importance()==SkillImportance.PREFERRED||skill.frequency()>1)return SkillPriority.MEDIUM;return SkillPriority.LOW;}private int importanceWeight(SkillImportance value){return value==SkillImportance.REQUIRED?3:value==SkillImportance.PREFERRED?2:1;}private String limit(String value){return value.length()>12000?value.substring(0,12000):value;}
 public record SkillDecision(String display,String normalized,MatchStatus status,SkillImportance importance,SkillPriority priority,String source,String evidence,String recommendation){}public record MatchScore(int overall,int keyword,int skill,Integer semantic,SemanticStatus semanticStatus,AlignmentService.Alignment experience,AlignmentService.Alignment education,List<SkillDecision>skills,String resumeText){}
}
