package com.careerpilot.modules.jobmatch.scoring;
import com.careerpilot.modules.jobmatch.entity.SkillImportance;import org.springframework.stereotype.Service;import java.util.*;
@Service public class JobSkillExtractor{private final SkillNormalizer normalizer;public JobSkillExtractor(SkillNormalizer normalizer){this.normalizer=normalizer;}
 public List<ExtractedSkill>extract(String jd){Map<String,Integer>frequency=new LinkedHashMap<>();Map<String,SkillImportance>importance=new HashMap<>();Map<String,String>source=new HashMap<>();SkillImportance section=SkillImportance.OPTIONAL;for(String physicalLine:jd.split("\\R")){String line=physicalLine.strip();if(line.isBlank())continue;Heading heading=heading(line);if(heading!=null){section=heading.importance();if(!heading.trailingText().isBlank())collect(heading.trailingText(),section,frequency,importance,source);continue;}for(String sentence:line.split("[.!?]+")){SkillImportance inline=inlineImportance(sentence);collect(sentence,inline==SkillImportance.OPTIONAL?section:inline,frequency,importance,source);}}
  List<ExtractedSkill>result=new ArrayList<>();frequency.forEach((skill,count)->result.add(new ExtractedSkill(skill,normalizer.display(skill),importance.getOrDefault(skill,SkillImportance.OPTIONAL),count,source.get(skill))));result.sort(Comparator.comparingInt((ExtractedSkill s)->rank(s.importance())).reversed().thenComparing(ExtractedSkill::display));return result;}
 private void collect(String text,SkillImportance level,Map<String,Integer>frequency,Map<String,SkillImportance>importance,Map<String,String>source){for(String skill:normalizer.extract(text)){frequency.merge(skill,1,Integer::sum);if(rank(level)>rank(importance.get(skill))){importance.put(skill,level);source.put(skill,source(level));}else source.putIfAbsent(skill,source(level));}}
 private Heading heading(String line){String cleaned=line.replaceFirst("^[\\s>*#-]+","").strip();int colon=cleaned.indexOf(':');String title=(colon>=0?cleaned.substring(0,colon):cleaned).strip().toLowerCase(Locale.ROOT);String trailing=colon>=0?cleaned.substring(colon+1).strip():"";if(title.matches("preferred skills?|preferred qualifications?|nice to have|bonus(?: skills?)?|desirable(?: skills?)?"))return new Heading(SkillImportance.PREFERRED,trailing);if(title.matches("required skills?|requirements?|must have|mandatory(?: skills?)?|minimum qualifications?|qualifications?"))return new Heading(SkillImportance.REQUIRED,trailing);if(colon>=0&&title.matches("responsibilities|experience|education|about(?: the role)?|job description|summary|duties|what you will do"))return new Heading(SkillImportance.OPTIONAL,trailing);return null;}
 private SkillImportance inlineImportance(String text){String lower=text.toLowerCase(Locale.ROOT);if(lower.matches(".*\\b(preferred|nice to have|bonus|desirable)\\b.*"))return SkillImportance.PREFERRED;if(lower.matches(".*\\b(must|required|mandatory|proficient|strong knowledge)\\b.*"))return SkillImportance.REQUIRED;return SkillImportance.OPTIONAL;}
 private String source(SkillImportance value){return value==SkillImportance.REQUIRED?"QUALIFICATION":value==SkillImportance.PREFERRED?"PREFERENCE":"DESCRIPTION";}
 private record Heading(SkillImportance importance,String trailingText){}
 private int rank(SkillImportance value){return value==SkillImportance.REQUIRED?3:value==SkillImportance.PREFERRED?2:value==SkillImportance.OPTIONAL?1:0;}}
