package com.careerpilot.modules.jobmatch.scoring;
import org.springframework.stereotype.Service;import java.util.*;import java.util.regex.*;
@Service
public class SkillNormalizer{
 private static final Map<String,List<String>>ALIASES=new LinkedHashMap<>();
 static{add("Java","java");add("Spring Boot","spring boot","springboot");add("PostgreSQL","postgresql","postgres");add("React","react","react.js","reactjs");add("TypeScript","typescript","ts");add("JavaScript","javascript","js");add("Docker","docker","containers");add("AWS","aws","amazon web services");add("Git","git","github","gitlab");add("REST APIs","rest api","rest apis","restful api","restful services");add("Microservices","microservice","microservices");add("Machine Learning","machine learning","ml");add("Python","python");add("SQL","sql");add("Power BI","power bi","powerbi");add("TensorFlow","tensorflow");add("Kubernetes","kubernetes","k8s");add("Node.js","node.js","nodejs");add("Angular","angular");add("Azure","azure");add("GCP","gcp","google cloud platform");add("MongoDB","mongodb","mongo db");add("Redis","redis");add("Kafka","kafka","apache kafka");add("JPA","jpa","hibernate");add("Maven","maven");add("Gradle","gradle");add("CI/CD","ci/cd","continuous integration");}
 private static void add(String canonical,String...aliases){ALIASES.put(canonical,List.of(aliases));}
 public String normalize(String value){if(value==null)return "";String cleaned=value.toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9+#./-]+"," ").trim();for(var entry:ALIASES.entrySet())for(String alias:entry.getValue())if(cleaned.equals(alias))return normalized(entry.getKey());return cleaned.replaceAll("[^a-z0-9+#]+"," ").trim();}
 public String display(String normalized){return ALIASES.keySet().stream().filter(v->normalized(v).equals(normalized)).findFirst().orElse(normalized);}
 public Set<String> extract(String text){if(text==null||text.isBlank())return Set.of();String lower=" "+text.toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9+#./-]+"," ")+" ";Set<String>found=new LinkedHashSet<>();for(var entry:ALIASES.entrySet())for(String alias:entry.getValue()){String escaped=Pattern.quote(alias);if(Pattern.compile("(?<![a-z0-9])"+escaped+"(?![a-z0-9])",Pattern.CASE_INSENSITIVE).matcher(lower).find()){if(alias.equals("spring")&&!lower.matches(".*\\bspring\\s+(boot|framework|mvc|data|security)\\b.*"))continue;found.add(normalized(entry.getKey()));break;}}return found;}
 public Set<String> related(String normalized){return switch(normalized){case"typescript"->Set.of("javascript");case"javascript"->Set.of("typescript");case"postgresql"->Set.of("sql");case"sql"->Set.of("postgresql","mongodb");case"spring boot"->Set.of("java");case"docker"->Set.of("kubernetes");case"kubernetes"->Set.of("docker");case"machine learning"->Set.of("python","tensorflow");case"tensorflow"->Set.of("machine learning","python");default->Set.of();};}
 private static String normalized(String value){return value.toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9+#]+"," ").trim();}
}
