package com.careerpilot.modules.resume.analysis.ai;
import com.careerpilot.config.*;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Test;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.web.client.HttpClientErrorException;
import org.springframework.web.client.HttpServerErrorException;
import org.springframework.web.client.ResourceAccessException;
import java.nio.charset.StandardCharsets;
import java.time.Duration;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.atomic.AtomicInteger;
import static org.assertj.core.api.Assertions.*;
class GeminiResumeAiFeedbackServiceTest {
 private GeminiResumeAiFeedbackService service(){return service(false,"");}
 private GeminiResumeAiFeedbackService service(boolean enabled,String key){var weights=new AnalysisProperties.Weights(30,20,20,15,15,40,20,10,10,10,10);var analysis=new AnalysisProperties("ats-rules-v1","resume-analysis-v1",30000,List.of("built"),weights);return new GeminiResumeAiFeedbackService(new AiProperties(enabled,key,"gemini-2.5-flash",Duration.ofSeconds(1),Duration.ofSeconds(1)),analysis,new ObjectMapper());}
 @Test void disabledProviderDoesNotRequireAKey(){assertThat(service().analyze("resume").status()).isEqualTo(AiFeedbackResult.Status.DISABLED);}
 @Test void enabledProviderWithoutKeyFailsSafely(){var result=service(true,"").analyze("resume");assertThat(result.status()).isEqualTo(AiFeedbackResult.Status.FAILED);assertThat(result.message()).doesNotContain("key=");}
 @Test void malformedOrOversizedStructuredOutputIsRejected(){assertThatThrownBy(()->service().parseAndValidate("{\"strengths\":null}")).isInstanceOf(Exception.class);String huge="x".repeat(1300);String json="{\"strengths\":[{\"title\":\"Strong\",\"description\":\""+huge+"\"}],\"weaknesses\":[],\"grammarSuggestions\":[],\"bulletRewrites\":[],\"summarySuggestions\":[]}";assertThatThrownBy(()->service().parseAndValidate(json)).isInstanceOf(IllegalArgumentException.class);}
 @Test void acceptsStrictStructuredFeedback() throws Exception {String json="{\"strengths\":[{\"title\":\"Clear stack\",\"description\":\"Names Java and Spring\"}],\"weaknesses\":[{\"title\":\"Limited impact\",\"description\":\"Bullets lack measurable outcomes\",\"severity\":\"MEDIUM\"}],\"grammarSuggestions\":[{\"originalText\":\"Built APIs\",\"suggestedText\":\"Developed APIs\",\"reason\":\"Uses a precise verb\"}],\"bulletRewrites\":[],\"summarySuggestions\":[\"State the target role\"]}";assertThat(service().parseAndValidate(json).weaknesses().getFirst().severity()).isEqualTo(AiFeedback.Severity.MEDIUM);}
 @Test void rejectsFabricatedMetricsAndDeduplicatesFeedback(){var rewrite=new AiFeedback.TextSuggestion("Built APIs","Built APIs that improved performance by 40%","Unsupported metric");var feedback=new AiFeedback(List.of(new AiFeedback.Insight("Clear stack","Names Java"),new AiFeedback.Insight("Clear stack","Names Java")),List.of(),List.of(),List.of(rewrite),List.of());assertThat(service().deduplicate(feedback).strengths()).hasSize(1);assertThatThrownBy(()->service().validateGrounding(feedback,"[EXPERIENCE] Built APIs")).isInstanceOf(IllegalArgumentException.class).hasMessageContaining("numeric");}
 @Test void usesModelCompatibleThinkingConfiguration(){assertThat(service(true,"key").thinkingConfig()).containsEntry("thinkingBudget",0);var weights=new AnalysisProperties.Weights(30,20,20,15,15,40,20,10,10,10,10);var analysis=new AnalysisProperties("ats-rules-v1","resume-analysis-v1",30000,List.of("built"),weights);var current=new GeminiResumeAiFeedbackService(new AiProperties(true,"key","gemini-3.6-flash",Duration.ofSeconds(1),Duration.ofSeconds(1)),analysis,new ObjectMapper());assertThat(current.thinkingConfig()).containsEntry("thinkingLevel","MINIMAL");}
 @Test void retries503ThenSucceeds(){var scenario=scenario(serverError(HttpStatus.SERVICE_UNAVAILABLE),success());assertThat(scenario.service().analyze("[EXPERIENCE] Built APIs").status()).isEqualTo(AiFeedbackResult.Status.SUCCESS);assertThat(scenario.calls()).isEqualTo(2);assertThat(scenario.delays()).singleElement().satisfies(delay->assertThat(delay).isBetween(1000L,1250L));}
 @Test void respectsRetryAfterFor429ThenSucceeds(){HttpHeaders headers=new HttpHeaders();headers.set("Retry-After","3");var scenario=scenario(clientError(HttpStatus.TOO_MANY_REQUESTS,headers),success());assertThat(scenario.service().analyze("[EXPERIENCE] Built APIs").status()).isEqualTo(AiFeedbackResult.Status.SUCCESS);assertThat(scenario.calls()).isEqualTo(2);assertThat(scenario.delays()).containsExactly(3000L);}
 @Test void repeated503FailsForPartialFallbackAfterThreeAttempts(){var scenario=scenario(serverError(HttpStatus.SERVICE_UNAVAILABLE),serverError(HttpStatus.SERVICE_UNAVAILABLE),serverError(HttpStatus.SERVICE_UNAVAILABLE));assertThat(scenario.service().analyze("[EXPERIENCE] Built APIs").status()).isEqualTo(AiFeedbackResult.Status.FAILED);assertThat(scenario.calls()).isEqualTo(3);assertThat(scenario.delays()).hasSize(2);}
 @Test void exhausted503UsesDiscoveredFallbackAndSucceeds(){var scenario=scenarioWithModels(models("gemini-3.5-flash"),serverError(HttpStatus.SERVICE_UNAVAILABLE),serverError(HttpStatus.SERVICE_UNAVAILABLE),serverError(HttpStatus.SERVICE_UNAVAILABLE),success());var result=scenario.service().analyze("[EXPERIENCE] Built APIs");assertThat(result.status()).isEqualTo(AiFeedbackResult.Status.SUCCESS);assertThat(result.primaryModelAttempted()).isEqualTo("gemini-3.6-flash");assertThat(result.fallbackModelUsed()).isEqualTo("gemini-3.5-flash");assertThat(result.model()).isEqualTo("gemini-3.5-flash");assertThat(result.requestOutcome()).isEqualTo("FALLBACK_SUCCESS");assertThat(scenario.calls()).isEqualTo(4);}
 @Test void primaryAndFallbackTransientFailuresReturnFailedForPartial(){var scenario=scenarioWithModels(models("gemini-3.5-flash"),serverError(HttpStatus.SERVICE_UNAVAILABLE),serverError(HttpStatus.SERVICE_UNAVAILABLE),serverError(HttpStatus.SERVICE_UNAVAILABLE),serverError(HttpStatus.SERVICE_UNAVAILABLE));var result=scenario.service().analyze("[EXPERIENCE] Built APIs");assertThat(result.status()).isEqualTo(AiFeedbackResult.Status.FAILED);assertThat(result.fallbackModelUsed()).isEqualTo("gemini-3.5-flash");assertThat(scenario.calls()).isEqualTo(4);}
 @Test void authenticationFailureIsNotRetried(){var scenario=scenario(clientError(HttpStatus.UNAUTHORIZED,new HttpHeaders()));assertThat(scenario.service().analyze("resume").status()).isEqualTo(AiFeedbackResult.Status.FAILED);assertThat(scenario.calls()).isEqualTo(1);assertThat(scenario.delays()).isEmpty();}
 @Test void forbiddenFailureIsNotRetriedOrFallenBack(){var scenario=scenario(clientError(HttpStatus.FORBIDDEN,new HttpHeaders()));assertThat(scenario.service().analyze("resume").status()).isEqualTo(AiFeedbackResult.Status.FAILED);assertThat(scenario.calls()).isEqualTo(1);assertThat(scenario.delays()).isEmpty();}
 @Test void unavailableModelIsNotRetried(){var scenario=scenario(clientError(HttpStatus.NOT_FOUND,new HttpHeaders()));assertThat(scenario.service().analyze("resume").status()).isEqualTo(AiFeedbackResult.Status.FAILED);assertThat(scenario.calls()).isEqualTo(1);assertThat(scenario.delays()).isEmpty();}
 @Test void retriesTransportFailureThenSucceeds(){var scenario=scenario(new ResourceAccessException("temporary connection failure"),success());assertThat(scenario.service().analyze("[EXPERIENCE] Built APIs").status()).isEqualTo(AiFeedbackResult.Status.SUCCESS);assertThat(scenario.calls()).isEqualTo(2);}
 @Test void successfulFirstAttemptDoesNotRetry(){var scenario=scenario(success());assertThat(scenario.service().analyze("[EXPERIENCE] Built APIs").status()).isEqualTo(AiFeedbackResult.Status.SUCCESS);assertThat(scenario.calls()).isEqualTo(1);assertThat(scenario.delays()).isEmpty();}

 private Scenario scenario(Object... outcomes){return scenarioWithModels(models(),outcomes);}
 private Scenario scenarioWithModels(com.fasterxml.jackson.databind.JsonNode models,Object... outcomes){var queue=new ArrayDeque<>(List.of(outcomes));var calls=new AtomicInteger();var delays=new ArrayList<Long>();var weights=new AnalysisProperties.Weights(30,20,20,15,15,40,20,10,10,10,10);var analysis=new AnalysisProperties("ats-rules-v1","resume-analysis-v1",30000,List.of("built"),weights);GeminiResumeAiFeedbackService.GeminiRequest request=(model,body)->{calls.incrementAndGet();Object outcome=queue.removeFirst();if(outcome instanceof RuntimeException exception)throw exception;return (com.fasterxml.jackson.databind.JsonNode)outcome;};var service=new GeminiResumeAiFeedbackService(new AiProperties(true,"test-key","gemini-3.6-flash",Duration.ofSeconds(1),Duration.ofSeconds(1)),analysis,new ObjectMapper(),request,()->models,delays::add,()->0);return new Scenario(service,calls,delays);}
 private com.fasterxml.jackson.databind.JsonNode models(String... names){var root=new ObjectMapper().createObjectNode();var values=root.putArray("models");for(String name:names){var model=values.addObject();model.put("name","models/"+name);model.putArray("supportedGenerationMethods").add("generateContent");}return root;}
 private com.fasterxml.jackson.databind.JsonNode success(){try{return new ObjectMapper().readTree("{\"candidates\":[{\"finishReason\":\"STOP\",\"content\":{\"parts\":[{\"text\":\"{\\\"strengths\\\":[{\\\"title\\\":\\\"Clear experience\\\",\\\"description\\\":\\\"The resume describes API work\\\"}],\\\"weaknesses\\\":[],\\\"grammarSuggestions\\\":[],\\\"bulletRewrites\\\":[],\\\"summarySuggestions\\\":[]}\"}]}}]}");}catch(Exception exception){throw new RuntimeException(exception);}}
 private HttpServerErrorException serverError(HttpStatus status){return HttpServerErrorException.create(status,status.getReasonPhrase(),new HttpHeaders(),providerError(status),StandardCharsets.UTF_8);}
 private HttpClientErrorException clientError(HttpStatus status,HttpHeaders headers){return HttpClientErrorException.create(status,status.getReasonPhrase(),headers,providerError(status),StandardCharsets.UTF_8);}
 private byte[] providerError(HttpStatus status){return ("{\"error\":{\"code\":"+status.value()+",\"status\":\""+(status==HttpStatus.SERVICE_UNAVAILABLE?"UNAVAILABLE":"ERROR")+"\",\"message\":\"Sanitized provider failure\"}}").getBytes(StandardCharsets.UTF_8);}
 private record Scenario(GeminiResumeAiFeedbackService service,AtomicInteger counter,List<Long> delays){int calls(){return counter.get();}}
}
