import { useQuery } from '@tanstack/react-query'
import { Link } from 'react-router-dom'
import { motion } from 'framer-motion'
import { api } from '../services/api'
import { useLatestActiveAnalysis, useResumes } from '../features/resume/api'
import type { Profile } from '../features/profile/types'

const actions=[['Job Match','Compare your profile with a role'],['Skill Gap','Find the skills to learn next'],['Assessments','Practice with tailored questions']]
export function DashboardPage(){const{data}=useQuery({queryKey:['profile'],queryFn:async()=>(await api.get<Profile>('/profile')).data});const resumes=useResumes();const latest=useLatestActiveAnalysis();const active=resumes.data?.find(r=>r.active);return <main className="page"><p className="eyebrow">Your command center</p><h1 className="page-title">Good to see you, {data?.fullName?.split(' ')[0]??'Pilot'}.</h1><p className="page-subtitle">Complete your profile and improve your active resume with explainable feedback.</p><section className="mt-8 grid gap-5 xl:grid-cols-3"><div className="card"><div className="flex justify-between"><div><p className="text-sm text-slate-400">Profile completion</p><p className="mt-2 text-4xl font-semibold">{data?.profileCompletionPercentage??0}%</p></div><Link className="text-sm text-cyan-300" to="/student/profile">Improve →</Link></div><div className="mt-6 h-2 overflow-hidden rounded-full bg-slate-800"><div className="h-full rounded-full bg-cyan-400" style={{width:`${data?.profileCompletionPercentage??0}%`}}/></div></div><Link to={active?`/student/resumes/${active.id}`:'/student/resumes'} className="card transition hover:border-cyan-300/30"><p className="text-sm text-slate-400">Active resume</p><h2 className="mt-3 text-xl font-semibold">{active?.originalFilename??'No active resume'}</h2><p className="mt-2 text-sm text-cyan-300">{active?'Open resume →':'Upload your first resume →'}</p></Link><div className="card bg-gradient-to-br from-cyan-400/15 to-indigo-500/10"><p className="text-sm text-cyan-200">Latest analysis</p>{latest.data?<><div className="mt-4 flex gap-8"><div><p className="text-3xl font-semibold">{latest.data.overallScore}</p><p className="text-xs text-slate-400">Resume</p></div><div><p className="text-3xl font-semibold">{latest.data.atsScore}</p><p className="text-xs text-slate-400">ATS</p></div></div><Link className="mt-4 inline-block text-sm text-cyan-300" to={`/student/resumes/${latest.data.resumeId}/analysis/${latest.data.id}`}>{new Date(latest.data.createdAt).toLocaleDateString()} →</Link></>:<p className="mt-3 text-sm text-slate-300">Analyze your active resume to get your first score.</p>}</div></section><h2 className="mt-10 text-xl font-semibold">Coming next</h2><section className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{actions.map(([title,copy],index)=><motion.article initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={{delay:index*.05}} className="card opacity-75" key={title}><span className="pill">Coming soon</span><h3 className="mt-5 font-semibold">{title}</h3><p className="mt-2 text-sm text-slate-400">{copy}</p></motion.article>)}</section></main>}
