import { useQuery } from '@tanstack/react-query'
import { Link } from 'react-router-dom'
import { motion } from 'framer-motion'
import { api } from '../services/api'
import { useLatestActiveAnalysis, useResumes } from '../features/resume/api'
import type { Profile } from '../features/profile/types'
import { useLatestJobMatch } from '../features/jobMatch/api'

const actions=[['Assessments','Practice with tailored questions'],['Interview scheduling','Plan interview preparation'],['Career roadmap','Build a longer-term learning plan']]
export function DashboardPage(){const{data}=useQuery({queryKey:['profile'],queryFn:async()=>(await api.get<Profile>('/profile')).data});const resumes=useResumes(),latest=useLatestActiveAnalysis(),jobMatch=useLatestJobMatch();const active=resumes.data?.find(r=>r.active);return <main className="page"><p className="eyebrow">Your command center</p><h1 className="page-title">Good to see you, {data?.fullName?.split(' ')[0]??'Pilot'}.</h1><p className="page-subtitle">Improve your resume and compare it with real roles using explainable heuristics.</p><section className="mt-8 grid gap-5 xl:grid-cols-4"><div className="card"><p className="text-sm text-slate-400">Profile completion</p><p className="mt-2 text-4xl font-semibold">{data?.profileCompletionPercentage??0}%</p><Link className="mt-4 inline-block text-sm text-cyan-300" to="/student/profile">Improve →</Link></div><Link to={active?`/student/resumes/${active.id}`:'/student/resumes'} className="card transition hover:border-cyan-300/30"><p className="text-sm text-slate-400">Active resume</p><h2 className="mt-3 text-xl font-semibold">{active?.originalFilename??'No active resume'}</h2><p className="mt-2 text-sm text-cyan-300">Open resume →</p></Link><div className="card"><p className="text-sm text-cyan-200">Latest analysis</p>{latest.data?<><p className="mt-3 text-3xl font-semibold">{latest.data.atsScore}%</p><Link className="mt-3 inline-block text-sm text-cyan-300" to={`/student/resumes/${latest.data.resumeId}/analysis/${latest.data.id}`}>View ATS analysis →</Link></>:<p className="mt-3 text-sm text-slate-400">No analysis yet.</p>}</div><Link className="card bg-gradient-to-br from-cyan-400/15 to-indigo-500/10 transition hover:border-cyan-300/30" to={jobMatch.data?`/student/job-match/${jobMatch.data.id}`:'/student/job-match'}><p className="text-sm text-cyan-200">Latest job match</p>{jobMatch.data?<><p className="mt-3 text-3xl font-semibold">{jobMatch.data.overallMatchScore}%</p><p className="mt-1 text-sm text-slate-300">{jobMatch.data.jobTitle}{jobMatch.data.companyName?` · ${jobMatch.data.companyName}`:''}</p></>:<><p className="mt-3 font-semibold">Compare with a role</p><p className="mt-2 text-sm text-cyan-300">Start Job Match →</p></>}</Link></section><h2 className="mt-10 text-xl font-semibold">Coming next</h2><section className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{actions.map(([title,copy],index)=><motion.article initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={{delay:index*.05}} className="card opacity-75" key={title}><span className="pill">Coming soon</span><h3 className="mt-5 font-semibold">{title}</h3><p className="mt-2 text-sm text-slate-400">{copy}</p></motion.article>)}</section></main>}
