import { useRef, useState, type DragEvent } from 'react'
import { Link } from 'react-router-dom'
import axios from 'axios'
import { downloadResume, useActivateResume, useDeleteResume, useResumes, useUploadResume } from '../features/resume/api'
import type { ResumeSummary } from '../features/resume/types'

const MAX_BYTES=5*1024*1024
export function ResumesPage(){const input=useRef<HTMLInputElement>(null);const resumes=useResumes();const upload=useUploadResume();const activate=useActivateResume();const remove=useDeleteResume();const[progress,setProgress]=useState(0);const[message,setMessage]=useState('');const[error,setError]=useState('');
  const select=(file?:File)=>{setMessage('');setError('');if(!file)return;const ext=file.name.toLowerCase();if(!ext.endsWith('.pdf')&&!ext.endsWith('.docx')){setError('Choose a PDF or DOCX file.');return}if(file.size===0){setError('The selected file is empty.');return}if(file.size>MAX_BYTES){setError('The selected file exceeds 5 MB.');return}setProgress(0);upload.mutate({file,onProgress:setProgress},{onSuccess:data=>setMessage(`${data.originalFilename} is parsed and ready.`),onError:value=>setError(apiMessage(value))})}
  const drop=(event:DragEvent)=>{event.preventDefault();select(event.dataTransfer.files[0])};const confirmDelete=(resume:ResumeSummary)=>{if(window.confirm(`Delete ${resume.originalFilename}? This removes the stored file and parsed sections.`))remove.mutate(resume.id,{onError:value=>setError(apiMessage(value))})}
  return <main className="page"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Resume Manager</p><h1 className="page-title">Your resumes</h1><p className="page-subtitle">Upload and prepare your resume for future analysis. Parsing is deterministic, not AI-generated.</p></div><button className="primary-button" onClick={()=>input.current?.click()}>Upload resume</button></div><input ref={input} hidden type="file" accept=".pdf,.docx,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document" onChange={e=>select(e.target.files?.[0])}/><section onDragOver={e=>e.preventDefault()} onDrop={drop} onClick={()=>input.current?.click()} className="card mt-8 cursor-pointer border-dashed text-center"><p className="text-lg font-semibold">Drop a PDF or DOCX here</p><p className="mt-2 text-sm text-slate-400">Maximum 5 MB. Files are validated by content signature.</p>{upload.isPending&&<div className="mx-auto mt-5 max-w-md"><div className="h-2 overflow-hidden rounded bg-slate-800"><div className="h-full bg-cyan-400" style={{width:`${progress}%`}}/></div><p className="mt-2 text-sm">Uploading and parsing… {progress}%</p></div>}</section>{message&&<p className="success-message mt-5">{message}</p>}{error&&<p className="error-message mt-5">{error}</p>}<section className="mt-8 space-y-4">{resumes.isLoading&&<div className="card">Loading resumes…</div>}{resumes.data?.length===0&&<div className="card text-center text-slate-400">No resumes uploaded yet.</div>}{resumes.data?.map(resume=><article className="card flex flex-col gap-5 xl:flex-row xl:items-center xl:justify-between" key={resume.id}><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold">{resume.originalFilename}</h2>{resume.active&&<span className="pill">Active</span>}<span className="rounded-full bg-white/5 px-2.5 py-1 text-xs text-slate-300">{resume.parseStatus}</span></div><p className="mt-2 text-sm text-slate-400">{formatSize(resume.fileSize)} · {resume.mimeType.includes('pdf')?'PDF':'DOCX'} · {new Date(resume.uploadedAt).toLocaleString()}</p></div><div className="flex flex-wrap gap-2"><Link className="secondary-button" to={`/student/resumes/${resume.id}`}>View</Link>{!resume.active&&<button className="secondary-button" disabled={activate.isPending} onClick={()=>activate.mutate(resume.id)}>Set active</button>}<button className="secondary-button" onClick={()=>void downloadResume(resume).catch(value=>setError(apiMessage(value)))}>Download</button><button className="secondary-button text-rose-300" disabled={remove.isPending} onClick={()=>confirmDelete(resume)}>Delete</button></div></article>)}</section></main>}
function formatSize(bytes:number){return bytes<1024*1024?`${(bytes/1024).toFixed(1)} KB`:`${(bytes/1024/1024).toFixed(1)} MB`}
function apiMessage(value:unknown){if(axios.isAxiosError(value))return value.response?.data?.message??'The resume request failed.';return 'The resume request failed.'}
