package com.careerpilot.modules.resume.analysis.scoring;

import com.careerpilot.config.AnalysisProperties;
import com.careerpilot.modules.resume.analysis.entity.*;
import com.careerpilot.modules.resume.entity.*;
import com.careerpilot.modules.resume.parser.ContactExtractor;
import org.springframework.stereotype.Service;
import java.util.*;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

@Service
public class DeterministicResumeScoringService {
 private static final Set<String> TECH=Set.of("java","javascript","typescript","python","spring","react","angular","vue","node","postgresql","mysql","mongodb","redis","docker","kubernetes","aws","azure","gcp","git","sql","rest","graphql","linux","maven","gradle","jenkins","terraform","kafka");
 private static final Set<String> GENERIC=Set.of("hardworking","team player","quick learner","good communication","responsible for","worked on");
 private static final Pattern METRIC=Pattern.compile("(?i)(?:\\b\\d+(?:\\.\\d+)?%?\\b|\\$\\s?\\d+|\\b(?:users|customers|requests|transactions|hours|days|seconds|milliseconds|revenue|cost|latency|throughput)\\b)");
 private final AnalysisProperties config;private final ContactExtractor contacts;
 public DeterministicResumeScoringService(AnalysisProperties config,ContactExtractor contacts){this.config=config;this.contacts=contacts;}
 public ScoreResult score(Resume resume){List<FindingDraft> findings=new ArrayList<>();String all=resume.getSections().stream().map(ResumeSection::getRawText).collect(Collectors.joining("\n"));
  int sections=sectionScore(resume,all,findings),keywords=keywordScore(all,findings);List<String> bullets=bullets(resume);int actions=actionScore(bullets,findings),quant=quantificationScore(bullets,findings),readability=readabilityScore(resume,all,findings);
  var w=config.weights();int ats=weighted(new int[]{sections,keywords,actions,quant,readability},new int[]{w.atsSection(),w.atsKeyword(),w.atsActionVerb(),w.atsQuantification(),w.atsReadability()});int overall=weighted(new int[]{ats,sections,keywords,actions,quant,readability},new int[]{w.overallAts(),w.overallSection(),w.overallKeyword(),w.overallActionVerb(),w.overallQuantification(),w.overallReadability()});
  findings.add(FindingDraft.of(FindingType.STRENGTH,"SCORING",FindingSeverity.INFO,"Explainable local score","Scores use section, keyword, action-verb, quantification, and readability rules; they are not an official ATS-vendor score."));return new ScoreResult(overall,ats,sections,keywords,actions,quant,readability,List.copyOf(findings));
 }
 private int sectionScore(Resume r,String all,List<FindingDraft> f){Set<SectionType> types=r.getSections().stream().map(ResumeSection::getSectionType).collect(Collectors.toSet());int score=0;var contact=contacts.extract(all);boolean hasContact=contact.email()!=null&&contact.phone()!=null;if(hasContact)score+=20;else missing(f,"Contact details","Include a reliable email and phone number.",FindingSeverity.HIGH);
  score+=present(types,SectionType.SUMMARY,10,f,"Summary",FindingSeverity.LOW);score+=present(types,SectionType.EDUCATION,15,f,"Education",FindingSeverity.MEDIUM);score+=present(types,SectionType.SKILLS,20,f,"Skills",FindingSeverity.HIGH);score+=present(types,SectionType.EXPERIENCE,25,f,"Experience",FindingSeverity.HIGH);score+=present(types,SectionType.PROJECTS,10,f,"Projects",FindingSeverity.LOW);return score;}
 private int present(Set<SectionType> types,SectionType type,int weight,List<FindingDraft> f,String title,FindingSeverity severity){if(types.contains(type))return weight;missing(f,title,"Add this section when it is relevant to your background.",severity);return 0;}
 private void missing(List<FindingDraft> f,String title,String description,FindingSeverity severity){f.add(FindingDraft.of(FindingType.MISSING_SECTION,"SECTIONS",severity,"Missing "+title+" section",description));}
 private int keywordScore(String text,List<FindingDraft> f){String lower=text.toLowerCase(Locale.ROOT);long technical=TECH.stream().filter(word->Pattern.compile("\\b"+Pattern.quote(word)+"\\b").matcher(lower).find()).count();int score=technical==0?25:technical<3?55:technical<6?80:100;long generic=GENERIC.stream().filter(lower::contains).count();score-=Math.min(30,(int)generic*10);Map<String,Long> frequencies=Arrays.stream(lower.replaceAll("[^a-z+#.]"," ").split("\\s+")).filter(s->s.length()>3).collect(Collectors.groupingBy(s->s,Collectors.counting()));boolean repeated=frequencies.values().stream().anyMatch(v->v>20);if(repeated){score-=15;f.add(FindingDraft.of(FindingType.KEYWORD,"KEYWORDS",FindingSeverity.MEDIUM,"Repeated keyword usage","A term appears excessively often; vary wording where accurate."));}if(technical>=6)f.add(FindingDraft.of(FindingType.STRENGTH,"KEYWORDS",FindingSeverity.INFO,"Specific technical vocabulary","The resume includes several concrete technology or engineering terms."));if(generic>0)f.add(FindingDraft.of(FindingType.WEAKNESS,"KEYWORDS",FindingSeverity.LOW,"Generic wording","Replace generic claims with specific responsibilities or outcomes already supported by your experience."));return clamp(score);}
 private List<String> bullets(Resume r){return r.getSections().stream().filter(s->s.getSectionType()==SectionType.EXPERIENCE||s.getSectionType()==SectionType.PROJECTS).flatMap(s->Arrays.stream(s.getRawText().split("\\n"))).map(line->line.replaceFirst("^[•*\\-–—▪◦]+\\s*","").trim()).filter(line->line.length()>12).toList();}
 private int actionScore(List<String> bullets,List<FindingDraft> f){if(bullets.isEmpty()){f.add(FindingDraft.of(FindingType.ACTION_VERB,"WRITING",FindingSeverity.MEDIUM,"No experience or project bullets detected","Use concise bullets that begin with accurate action verbs."));return 30;}Set<String> verbs=config.strongActionVerbs().stream().map(v->v.toLowerCase(Locale.ROOT)).collect(Collectors.toSet());long strong=bullets.stream().filter(line->verbs.contains(firstWord(line))).count();int score=(int)Math.round(strong*100d/bullets.size());if(score<60)f.add(FindingDraft.of(FindingType.ACTION_VERB,"WRITING",FindingSeverity.MEDIUM,"Strengthen bullet openings","Begin more bullets with precise action verbs that truthfully describe your contribution."));else f.add(FindingDraft.of(FindingType.STRENGTH,"WRITING",FindingSeverity.INFO,"Action-oriented bullets","Most detected bullets begin with clear action verbs."));return score;}
 private String firstWord(String line){return line.toLowerCase(Locale.ROOT).replaceAll("^[^a-z]+","").split("[^a-z]+",2)[0];}
 private int quantificationScore(List<String> bullets,List<FindingDraft> f){if(bullets.isEmpty())return 20;long quantified=bullets.stream().filter(line->METRIC.matcher(line).find()).count();int score=(int)Math.round(quantified*100d/bullets.size());if(score<40)f.add(FindingDraft.of(FindingType.QUANTIFICATION,"IMPACT",FindingSeverity.MEDIUM,"Limited measurable impact","Where facts are available, add truthful counts, percentages, scale, time, cost, or performance outcomes. Do not invent metrics."));else f.add(FindingDraft.of(FindingType.STRENGTH,"IMPACT",FindingSeverity.INFO,"Measurable impact present","Several detected bullets include concrete scale or outcomes."));return score;}
 private int readabilityScore(Resume r,String text,List<FindingDraft> f){int score=100;if(text.length()<500){score-=40;f.add(FindingDraft.of(FindingType.READABILITY,"READABILITY",FindingSeverity.HIGH,"Resume content is very short","Add relevant evidence and detail while keeping statements concise."));}if(text.length()>20000)score-=10;long longLines=Arrays.stream(text.split("\\n")).filter(line->line.length()>180).count();if(longLines>0){score-=Math.min(30,(int)longLines*5);f.add(FindingDraft.of(FindingType.READABILITY,"READABILITY",FindingSeverity.MEDIUM,"Long extracted lines","Break dense statements into focused bullets where the source format permits."));}long duplicateTypes=r.getSections().stream().collect(Collectors.groupingBy(ResumeSection::getSectionType,Collectors.counting())).values().stream().filter(n->n>1).count();if(duplicateTypes>0){score-=10;f.add(FindingDraft.of(FindingType.FORMATTING,"STRUCTURE",FindingSeverity.LOW,"Repeated section headings","Combine repeated sections when they represent the same topic."));}return clamp(score);}
 private int weighted(int[] scores,int[] weights){int total=0,sum=0;for(int i=0;i<scores.length;i++){total+=scores[i]*weights[i];sum+=weights[i];}return sum==0?0:clamp((int)Math.round(total/(double)sum));}
 private int clamp(int value){return Math.max(0,Math.min(100,value));}
}
